# Reading data into SQLite database

In [ ]:
import pandas as pd                 # Import Pandas library
import sqlite3                        # Import SQLite3 library 
con = sqlite3.connect('northwind.db') # Connect to SQLite database
                                      # Assign SQL variable
sql = "SELECT customerID, companyName, address, city, postalCode FROM customers WHERE city = 'London'" 
df = pd.read_sql_query(sql,con)                         # Read result into dataframe
con.close()                                             # Close connection
df                                                      # Display data frame

In [ ]:
import pandas as pd                   # Import Pandas library
import sqlite3                        # Import SQLite3 library 
con = sqlite3.connect('northwind.db') # Connect to SQLite database
                                      # Assign SQL variable
sql = "SELECT customerID, companyName, address, city FROM customers WHERE city IN ('London', 'Paris', 'Madrid')" 
df = pd.read_sql_query(sql,con)                         # Read result into dataframe
con.close()                                             # Close connection
df

In [ ]:
import pandas as pd
import sqlite3
con = sqlite3.connect('northwind.db')
sql = "SELECT * FROM products WHERE unitPrice BETWEEN 19 AND 20"
df = pd.read_sql_query(sql,con)
con.close()
df

In [ ]:
import pandas as pd
import sqlite3
con = sqlite3.connect('northwind.db')
sql = "SELECT categoryID, ROUND(sum(unitsInStock),2) AS [Total Units in Stock] FROM products  GROUP BY categoryID"
df = pd.read_sql_query(sql,con)
con.close()
df

In [ ]:
import pandas as pd
import sqlite3
con = sqlite3.connect('northwind.db')
s1 = "SELECT Orders.OrderID, Customers.contactName, Customers.contactTitle, Customers.companyName, Orders.OrderDate "
s2 = "FROM Orders INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID "
sql = s1 + s2
df = pd.read_sql_query(sql,con)
con.close()
df

In [ ]:
import pandas as pd
import sqlite3
con = sqlite3.connect('northwind.db')
s1 = "SELECT Orders.OrderID, order_details.productID, products.productName, Order_details.quantity, Order_details.unitPrice "
s2 = "FROM Orders "
s3 = "INNER JOIN  Order_details ON Orders.orderID = Order_details.orderID "
s4 = "INNER JOIN Products ON Order_details.productID = Products.productID "
sql = s1 + s2 + s3 + s4
df = pd.read_sql_query(sql,con)
con.close()
df

<center><h1>Use of Data Throughout Product Life Cycle</h1></center>

<img src="plc.png" width="70%" height="70%" >

<center><h1>Data Sources Demonstration</h1></center>

<img src="data_sources.png" width="70%" height="70%" >

<center><h1>Web Scraping in ParseHub</h1></center>

<img src="https://pbs.twimg.com/profile_images/1158810653395759104/kdaYE14y_400x400.jpg" width="30%" height="30%" >

<a href="https://openrefine.org/" target="_blank"><center><h1>Data Cleaning in OpenRefine</h1></center></a>

<img src="https://content.uiowa.edu/sites/content.uiowa.edu/files/logo-openrefine-550.png" width="30%" height="30%" >

## Import SQLite data into Pandas for Analysis
SELECT * 
FROM nba_run_results;

In [2]:
import pandas as pd
import sqlite3
con = sqlite3.connect('nba_db.db')
sql = "SELECT * FROM nba_run_results"
df = pd.read_sql_query(sql,con)
con.close()
df

,Col_Rank,Col_Player,Col_College,Col_Yrs,Col_Game,Col_Minutes_Played,Col_Points,Col_Total_Rebounds,Col_Assists,Col_Field_Goal_Percentage,Col_Three_Pt_Percentage,Col_Free_Throw_Percentage
0,1,Andrew Wiggins,Kansas,8.0,598.0,20935.0,11519.0,2649.0,1393.0,0.448,0.350,0.723
1,2,Jabari Parker,Duke,8.0,310.0,8535.0,4380.0,1703.0,610.0,0.494,0.326,0.743
2,3,Joel Embiid,Kansas,6.0,328.0,10240.0,8535.0,3732.0,1080.0,0.490,0.338,0.810
3,4,Aaron Gordon,Arizona,8.0,528.0,15277.0,6887.0,3310.0,1313.0,0.460,0.323,0.702
4,6,Marcus Smart,Oklahoma State,8.0,520.0,15484.0,5438.0,1867.0,2318.0,0.382,0.321,0.780
5,7,Julius Randle,Kentucky,8.0,518.0,16145.0,9191.0,4814.0,1842.0,0.472,0.332,0.743
6,8,Nik Stauskas,Michigan,6.0,343.0,6701.0,2290.0,691.0,515.0,0.389,0.354,0.812
7,9,Noah Vonleh,Indiana,7.0,339.0,5683.0,1660.0,1742.0,257.0,0.459,0.308,0.691
8,10,Elfrid Payton,Louisiana,8.0,500.0,13383.0,5036.0,2007.0,2868.0,0.447,0.287,0.623
9,11,Doug McDermott,Creighton,8.0,527.0,11012.0,4846.0,1236.0,496.0,0.476,0.409,0.820
10,13,Zach LaVine,UCLA,8.0,478.0,15219.0,9466.0,1876.0,1860.0,0.461,0.386,0.830
11,14,T.J. Warren,NC State,7.0,332.0,9553.0,5142.0,1372.0,397.0,0.507,0.357,0.780
12,15,Adreian Payne,Michigan State,4.0,107.0,1403.0,429.0,315.0,66.0,0.406,0.254,0.680
13,17,James Young,Kentucky,4.0,95.0,812.0,219.0,96.0,28.0,0.367,0.277,0.563
14,18,Tyler Ennis,Syracuse,4.0,186.0,2336.0,779.0,250.0,359.0,0.419,0.317,0.768
15,19,Gary Harris,Michigan State,8.0,468.0,13473.0,5526.0,1162.0,965.0,0.448,0.363,0.812
16,21,Mitch McGary,Michigan,2.0,52.0,557.0,227.0,183.0,17.0,0.527,0.000,0.580
17,22,Jordan Adams,UCLA,2.0,32.0,263.0,101.0,30.0,19.0,0.402,0.385,0.607
18,23,Rodney Hood,Duke,8.0,448.0,10977.0,4656.0,1160.0,736.0,0.420,0.366,0.841
19,24,Shabazz Napier,UConn,6.0,345.0,5986.0,2433.0,657.0,849.0,0.397,0.345,0.815
20,26,P.J. Hairston,UNC,2.0,111.0,2000.0,664.0,266.0,59.0,0.343,0.295,0.810
21,28,C.J. Wilcox,Washington,3.0,66.0,376.0,132.0,31.0,30.0,0.370,0.333,0.813
22,29,Josh Huestis,Stanford,3.0,76.0,1068.0,187.0,180.0,23.0,0.346,0.312,0.240
23,30,Kyle Anderson,UCLA,8.0,505.0,10583.0,3366.0,2220.0,1167.0,0.476,0.334,0.711
24,32,K.J. McDaniels,Clemson,3.0,148.0,2092.0,782.0,324.0,95.0,0.412,0.290,0.776
25,33,Joe Harris,Virginia,8.0,414.0,10601.0,4584.0,1344.0,679.0,0.483,0.439,0.780
26,34,Cleanthony Early,Wichita State,2.0,56.0,801.0,241.0,123.0,42.0,0.346,0.263,0.750
27,35,Jarnell Stokes,Tennessee,3.0,28.0,151.0,67.0,40.0,7.0,0.581,NaN,0.531
28,36,Johnny O'Bryant,LSU,4.0,147.0,1684.0,509.0,352.0,69.0,0.402,0.360,0.663
29,37,DeAndre Daniels,UConn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,38,Spencer Dinwiddie,Colorado,8.0,387.0,10206.0,5042.0,1167.0,1933.0,0.411,0.322,0.791
31,39,Jerami Grant,Syracuse,8.0,555.0,14454.0,6329.0,2189.0,747.0,0.452,0.349,0.723
32,40,Glenn Robinson III,Michigan,7.0,304.0,5299.0,1804.0,776.0,238.0,0.457,0.373,0.779
33,42,Nick Johnson,Arizona,1.0,28.0,262.0,74.0,39.0,11.0,0.347,0.238,0.680
34,44,Markel Brown,Oklahoma State,3.0,113.0,1794.0,584.0,234.0,132.0,0.380,0.295,0.781
35,45,Dwight Powell,Stanford,8.0,511.0,9720.0,3926.0,2349.0,524.0,0.585,0.296,0.751
36,46,Jordan Clarkson,Missouri,8.0,600.0,16191.0,9216.0,1971.0,1526.0,0.439,0.338,0.827
37,47,Russ Smith,Louisville,2.0,27.0,131.0,53.0,15.0,19.0,0.319,0.188,0.769
38,48,Lamar Patterson,Pitt,2.0,40.0,435.0,93.0,57.0,45.0,0.326,0.236,0.720
39,49,Cameron Bairstow,New Mexico,2.0,36.0,167.0,44.0,36.0,7.0,0.296,0.200,0.846
40,50,Alec Brown,Green Bay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,55,Semaj Christon,Xavier,1.0,64.0,973.0,183.0,87.0,130.0,0.345,0.190,0.548
42,56,Devyn Marble,Iowa,2.0,44.0,457.0,97.0,69.0,29.0,0.304,0.222,0.375
43,58,Jordan McRae,Tennessee,4.0,123.0,1696.0,846.0,225.0,167.0,0.417,0.355,0.772
44,59,Xavier Thames,San Diego State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,60,Cory Jefferson,Baylor,2.0,58.0,581.0,205.0,161.0,16.0,0.444,0.125,0.583

## SELECT entries with conditions
SELECT *
FROM nba_run_results
WHERE Col_Game > 50;

In [3]:
import pandas as pd
import sqlite3
con = sqlite3.connect('nba_db.db')
sql = "SELECT * FROM nba_run_results WHERE Col_Game > 400"
df = pd.read_sql_query(sql,con)
con.close()
df

,Col_Rank,Col_Player,Col_College,Col_Yrs,Col_Game,Col_Minutes_Played,Col_Points,Col_Total_Rebounds,Col_Assists,Col_Field_Goal_Percentage,Col_Three_Pt_Percentage,Col_Free_Throw_Percentage
0,1,Andrew Wiggins,Kansas,8,598,20935,11519,2649,1393,0.448,0.350,0.723
1,4,Aaron Gordon,Arizona,8,528,15277,6887,3310,1313,0.460,0.323,0.702
2,6,Marcus Smart,Oklahoma State,8,520,15484,5438,1867,2318,0.382,0.321,0.780
3,7,Julius Randle,Kentucky,8,518,16145,9191,4814,1842,0.472,0.332,0.743
4,10,Elfrid Payton,Louisiana,8,500,13383,5036,2007,2868,0.447,0.287,0.623
5,11,Doug McDermott,Creighton,8,527,11012,4846,1236,496,0.476,0.409,0.820
6,13,Zach LaVine,UCLA,8,478,15219,9466,1876,1860,0.461,0.386,0.830
7,19,Gary Harris,Michigan State,8,468,13473,5526,1162,965,0.448,0.363,0.812
8,23,Rodney Hood,Duke,8,448,10977,4656,1160,736,0.420,0.366,0.841
9,30,Kyle Anderson,UCLA,8,505,10583,3366,2220,1167,0.476,0.334,0.711
10,33,Joe Harris,Virginia,8,414,10601,4584,1344,679,0.483,0.439,0.780
11,39,Jerami Grant,Syracuse,8,555,14454,6329,2189,747,0.452,0.349,0.723
12,45,Dwight Powell,Stanford,8,511,9720,3926,2349,524,0.585,0.296,0.751
13,46,Jordan Clarkson,Missouri,8,600,16191,9216,1971,1526,0.439,0.338,0.827

In [4]:
import pandas as pd
import sqlite3
con = sqlite3.connect('nba_db.db')
sql = "SELECT Col_College, sum(Col_Game) AS [Total # of Games] FROM nba_run_results GROUP BY Col_College ORDER BY [Total # of Games] DESC "
df = pd.read_sql_query(sql,con)
con.close()
df

        Col_College  Total # of Games
0              UCLA            1015.0
1            Kansas             926.0
2              Duke             758.0
3          Syracuse             741.0
4          Michigan             699.0
5    Oklahoma State             633.0
6          Kentucky             613.0
7          Missouri             600.0
8          Stanford             587.0
9    Michigan State             575.0
10          Arizona             556.0
11        Creighton             527.0
12        Louisiana             500.0
13         Virginia             414.0
14         Colorado             387.0
15            UConn             345.0
16          Indiana             339.0
17         NC State             332.0
18        Tennessee             151.0
19          Clemson             148.0
20              LSU             147.0
21              UNC             111.0
22       Washington              66.0
23           Xavier              64.0
24           Baylor              58.0
25    Wichita State              56.0
26             Iowa              44.0
27             Pitt              40.0
28       New Mexico              36.0
29       Louisville              27.0
30        Green Bay               NaN
31  San Diego State               NaN

In [5]:
# CAST(ROUND(Column_Name, 2) AS DECIMAL(10,2)
import pandas as pd
import sqlite3
con = sqlite3.connect('nba_db.db')
# sql = "SELECT Col_Player, Col_College, Col_Game, Col_Yrs, ROUND((Col_Game*1.0/Col_Yrs),2) AS [Games/Years], ROUND((Col_Points*1.0/(Col_Game*1.0/Col_Yrs)),2) AS [Avg Poits] FROM nba_run_results ORDER BY  [Avg Poits] DESC "
sql = "SELECT Col_Player, Col_College, Col_Game, Col_Yrs, ROUND(CAST(Col_Game AS FLOAT)/Col_Yrs,2) AS [Games/Years], ROUND((CAST(Col_Points AS FLOAT)/(CAST(Col_Game AS FLOAT)/Col_Yrs)),2) AS [Avg Poits] FROM nba_run_results ORDER BY  [Avg Poits] DESC "
df = pd.read_sql_query(sql,con)
con.close()
df

,Col_Player,Col_College,Col_Game,Col_Yrs,Games/Years,Avg Poits
0,Zach LaVine,UCLA,478.0,8.0,59.75,158.43
1,Joel Embiid,Kansas,328.0,6.0,54.67,156.13
2,Andrew Wiggins,Kansas,598.0,8.0,74.75,154.10
3,Julius Randle,Kentucky,518.0,8.0,64.75,141.95
4,Jordan Clarkson,Missouri,600.0,8.0,75.00,122.88
5,Jabari Parker,Duke,310.0,8.0,38.75,113.03
6,T.J. Warren,NC State,332.0,7.0,47.43,108.42
7,Aaron Gordon,Arizona,528.0,8.0,66.00,104.35
8,Spencer Dinwiddie,Colorado,387.0,8.0,48.38,104.23
9,Gary Harris,Michigan State,468.0,8.0,58.50,94.46
10,Jerami Grant,Syracuse,555.0,8.0,69.38,91.23
11,Joe Harris,Virginia,414.0,8.0,51.75,88.58
12,Marcus Smart,Oklahoma State,520.0,8.0,65.00,83.66
13,Rodney Hood,Duke,448.0,8.0,56.00,83.14
14,Elfrid Payton,Louisiana,500.0,8.0,62.50,80.58
15,Doug McDermott,Creighton,527.0,8.0,65.88,73.56
16,Dwight Powell,Stanford,511.0,8.0,63.88,61.46
17,Kyle Anderson,UCLA,505.0,8.0,63.13,53.32
18,Shabazz Napier,UConn,345.0,6.0,57.50,42.31
19,Glenn Robinson III,Michigan,304.0,7.0,43.43,41.54
20,Nik Stauskas,Michigan,343.0,6.0,57.17,40.06
21,Noah Vonleh,Indiana,339.0,7.0,48.43,34.28
22,Jordan McRae,Tennessee,123.0,4.0,30.75,27.51
23,Tyler Ennis,Syracuse,186.0,4.0,46.50,16.75
24,Adreian Payne,Michigan State,107.0,4.0,26.75,16.04
25,K.J. McDaniels,Clemson,148.0,3.0,49.33,15.85
26,Markel Brown,Oklahoma State,113.0,3.0,37.67,15.50
27,Johnny O'Bryant,LSU,147.0,4.0,36.75,13.85
28,P.J. Hairston,UNC,111.0,2.0,55.50,11.96
29,James Young,Kentucky,95.0,4.0,23.75,9.22
30,Mitch McGary,Michigan,52.0,2.0,26.00,8.73
31,Cleanthony Early,Wichita State,56.0,2.0,28.00,8.61
32,Josh Huestis,Stanford,76.0,3.0,25.33,7.38
33,Jarnell Stokes,Tennessee,28.0,3.0,9.33,7.18
34,Cory Jefferson,Baylor,58.0,2.0,29.00,7.07
35,Jordan Adams,UCLA,32.0,2.0,16.00,6.31
36,C.J. Wilcox,Washington,66.0,3.0,22.00,6.00
37,Lamar Patterson,Pitt,40.0,2.0,20.00,4.65
38,Devyn Marble,Iowa,44.0,2.0,22.00,4.41
39,Russ Smith,Louisville,27.0,2.0,13.50,3.93
40,Semaj Christon,Xavier,64.0,1.0,64.00,2.86
41,Nick Johnson,Arizona,28.0,1.0,28.00,2.64
42,Cameron Bairstow,New Mexico,36.0,2.0,18.00,2.44
43,DeAndre Daniels,UConn,NaN,NaN,NaN,NaN
44,Alec Brown,Green Bay,NaN,NaN,NaN,NaN
45,Xavier Thames,San Diego State,NaN,NaN,NaN,NaN